# Generated by Django 3.2.22 on 2023-11-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('preview', models.ImageField(null=True, unique=True, upload_to=market.products.models.image_directory_path)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('category', models.ManyToManyField(related_name='products', to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_at', models.DateField(auto_now_add=True, verbose_name='дата просмотра продукта')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_view_history', to='products.product', verbose_name='продукт')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история просмотра продукта',
                'verbose_name_plural': 'история просмотров продукта',
                'ordering': ['user', 'product', 'view_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='отзыв создан')),
                ('product', models.ManyToManyField(related_name='product_feedbacks', to='products.Product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв на продукт',
                'verbose_name_plural': 'отзывы на продукт',
                'ordering': ['user', 'created_at'],
            },
        ),
    ]
