# Generated by Django 4.2.6 on 2023-10-15 12:06

from django.db import migrations, models
import market.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=market.products.models.image_directory_path)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('category', models.ManyToManyField(related_name='products', to='categories.category')),
            ],
        ),
    ]
