# Generated by Django 3.2.22 on 2023-12-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feedback',
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
