# Generated by Django 4.2.6 on 2023-10-22 17:59

from django.db import migrations, models
import market.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(null=True, unique=True, upload_to=market.products.models.image_directory_path),
        ),
    ]
