# Generated by Django 3.2.22 on 2023-12-21 18:59

from django.db import migrations, models
import market.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_auto_20231219_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='categories.Category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активирован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(null=True, unique=True, upload_to=market.products.models.image_directory_path, verbose_name='изображение'),
        ),
    ]
