# Generated by Django 3.2.22 on 2024-02-02 21:22

from django.db import migrations, models
import django.db.models.deletion
import market.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240128_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.products.models.product_image_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
