# Generated by Django 3.2.22 on 2023-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Выбрать аватар профиля', null=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите номер телефона', max_length=10, null=True, verbose_name='Номер телефона'),
        ),
    ]
