# Generated by Django 3.2.22 on 2023-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231105_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/no_image.png', help_text='Выбрать аватар профиля', null=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар профиля'),
        ),
    ]
