# Generated by Django 3.2.22 on 2023-12-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите номер телефона', max_length=256, null=True, verbose_name='Номер телефона'),
        ),
    ]
