# Generated by Django 3.2.22 on 2023-11-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSettings',
        ),
    ]
