# Generated by Django 4.2.6 on 2023-10-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_cache', models.IntegerField(default=86400)),
                ('seller_data_cache', models.IntegerField(default=86400)),
                ('banners_cache', models.IntegerField(default=600)),
                ('products_cache', models.IntegerField(default=86400)),
                ('top_products_cache', models.IntegerField(default=86400)),
                ('product_data_cache', models.IntegerField(default=86400)),
            ],
        ),
    ]
