# Generated by Django 3.2.22 on 2023-11-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_cache', models.IntegerField(default=86400, verbose_name='Время кэширования Категорий товаров')),
                ('seller_data_cache', models.IntegerField(default=86400, verbose_name='Время кэширования данных о Продавце')),
                ('banners_cache', models.IntegerField(default=600, verbose_name='Время кэширования Баннеров')),
                ('products_cache', models.IntegerField(default=86400, verbose_name='Время кэширования списка Товаров из Каталога')),
                ('top_products_cache', models.IntegerField(default=86400, verbose_name='Время кэширования списка Топ-Товаров')),
                ('product_data_cache', models.IntegerField(default=86400, verbose_name='Время кэширования данных о Товаре')),
            ],
        ),
    ]
