# Generated by Django 3.2.22 on 2024-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ordinary', 'Обычная доставка'), ('express', 'Экспресс доставка')], default='Unspecified', max_length=256, null=True, verbose_name='способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], default='Unspecified', max_length=256, null=True, verbose_name='способ оплаты'),
        ),
    ]
