# Generated by Django 3.2.22 on 2023-12-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerproduct_created_at'),
        ('orders', '0002_auto_20231221_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='sellers.discount'),
        ),
    ]
