# Generated by Django 3.2.22 on 2024-02-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_auto_20240116_1549'),
        ('orders', '0003_auto_20240203_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='sellers.sellerproduct', verbose_name='продукт продавца')),
            ],
            options={
                'verbose_name': 'продукт заказа',
                'verbose_name_plural': 'продукты заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(related_name='orders', to='orders.OrderProduct', verbose_name='продукт заказа'),
        ),
    ]
