# Generated by Django 3.2.22 on 2023-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellerproduct_sales'),
        ('orders', '0003_alter_orderstatus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='seller_products',
            field=models.ManyToManyField(related_name='orders', to='sellers.SellerProduct'),
        ),
    ]
