# Generated by Django 3.2.22 on 2024-02-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_auto_20240116_1549'),
        ('orders', '0004_auto_20240204_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_products',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='sellers.discounttype', verbose_name='тип скидки'),
        ),
    ]
