# Generated by Django 3.2.22 on 2024-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_seller_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_products',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_products',
            field=models.JSONField(default={}, verbose_name='продукт заказа'),
        ),
    ]
