# Generated by Django 3.2.22 on 2024-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20240211_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_products',
            field=models.JSONField(null=True, verbose_name='продукт заказа'),
        ),
    ]
