# Generated by Django 3.2.22 on 2023-11-18 12:19

from django.db import migrations, models
import django.db.models.deletion
import market.catalog_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название скидки')),
                ('type', models.SmallIntegerField(default=0, verbose_name='тип скидки')),
                ('value', models.SmallIntegerField(default=0, verbose_name='сумма скидки')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ['type', 'name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='продавец')),
                ('logo', models.ImageField(null=True, unique=True, upload_to=market.catalog_app.models.seller_logo_directory_path)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
                'ordering': ['is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена продукта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='продукт продавца создан')),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog_app.discount', verbose_name='скидка')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='products.product', verbose_name='продукт')),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='catalog_app.seller', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'продукт продавца',
                'verbose_name_plural': 'продукты продавцов',
                'ordering': ['product', 'price', 'seller'],
            },
        ),
    ]
