# Generated by Django 3.2.22 on 2023-11-10 12:52

from django.db import migrations, models
import market.sellers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, unique=True, upload_to=market.sellers.models.seller_logo_directory_path)),
                ('archived', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
