# Generated by Django 3.2.22 on 2023-12-02 20:04

from django.db import migrations, models
import django.db.models.deletion
import market.sellers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('value', models.IntegerField(default=0, verbose_name='скидка в %')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('logo', models.ImageField(null=True, unique=True, upload_to=market.sellers.models.seller_logo_directory_path, verbose_name='лого')),
                ('archived', models.BooleanField(default=False, verbose_name='архивация продавца')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('stock', models.IntegerField(default=0, verbose_name='сколько в наличии')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='sellers.discount', verbose_name='скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='products.product', verbose_name='продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='sellers.seller', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'продукт продавца',
                'verbose_name_plural': 'продукты продавца',
            },
        ),
    ]
