# Generated by Django 3.2.22 on 2023-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20231221_2202'),
        ('sellers', '0002_sellerproduct_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='Discounts', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.SmallIntegerField(null=True, verbose_name='тип скидки'),
        ),
    ]
