# Generated by Django 3.2.22 on 2023-11-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='sellers.discount'),
        ),
    ]
