# Generated by Django 3.2.22 on 2023-12-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20231230_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
