# Generated by Django 3.2.22 on 2023-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20231221_2202'),
        ('sellers', '0004_alter_discount_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount_products',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='Discounts', to='categories.Category', verbose_name='скидка на категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время окончания скидки'),
        ),
    ]
