# Generated by Django 3.2.22 on 2023-11-10 13:17

from django.db import migrations, models
import django.db.models.deletion
import market.sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_preview'),
        ('sellers', '0004_sellerproduct_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('name',), 'verbose_name': 'скидка', 'verbose_name_plural': 'скидки'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('name',), 'verbose_name': 'продавец', 'verbose_name_plural': 'продавцы'},
        ),
        migrations.AlterModelOptions(
            name='sellerproduct',
            options={'verbose_name': 'продукт продавца', 'verbose_name_plural': 'продукты продавца'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(default=0, verbose_name='скидка в %'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='архивация продавца'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to=market.sellers.models.seller_logo_directory_path, verbose_name='лого'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='sellers.discount', verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='products.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='sellers.seller', verbose_name='продавец'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='сколько в наличии'),
        ),
    ]
