# Generated by Django 3.2.22 on 2023-12-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_auto_20231230_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(default=0, max_length=100, verbose_name='скидка в %'),
        ),
    ]
