# Generated by Django 3.2.22 on 2023-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_auto_20231110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
