# Generated by Django 3.2.22 on 2023-11-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellerproduct_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproduct',
            name='sales',
        ),
    ]
