# Generated by Django 3.2.22 on 2024-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20231221_2202'),
        ('sellers', '0006_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='discounts', to='categories.Category', verbose_name='скидка на категории'),
        ),
    ]
