# Generated by Django 3.2.22 on 2024-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20231221_2202'),
        ('sellers', '0007_alter_discount_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='categories.Category', verbose_name='скидка на категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(default=0, verbose_name='скидка в %'),
        ),
    ]
