# Generated by Django 3.2.22 on 2024-01-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_auto_20240111_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип скидки',
                'verbose_name_plural': 'типы скидки',
            },
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('pk', 'value'), 'verbose_name': 'скидка', 'verbose_name_plural': 'скидки'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='sellers.discounttype', verbose_name='тип'),
        ),
    ]
