# Generated by Django 3.2.22 on 2024-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_auto_20240116_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='название'),
        ),
    ]
