# Generated by Django 3.2.22 on 2024-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_alter_discounttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount_products',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество товаров в корзине'),
        ),
    ]
